services:
  frontend:
    profiles: [dev]
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3002:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    profiles: [dev]
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3001" 
    volumes:
      - ./backend:/app
      - /app/node_modules
