services:
  frontend:
    image: order-app/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    image: order-app/backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
